"""add service_alert table

Revision ID: a98f898dc627
Revises: 2ae6f724129d
Create Date: 2026-03-08 00:57:20.052629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a98f898dc627'
down_revision: Union[str, Sequence[str], None] = '2ae6f724129d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('header_text', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('description_text', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('cause', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('route_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_alert')
    # ### end Alembic commands ###
