"""add max_length to feed_name, username, password

Revision ID: 2ae6f724129d
Revises: a1b2c3d4e5f6
Create Date: 2026-03-03 18:14:10.886833

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2ae6f724129d'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
